core:
  workspace:
    dev: "[D] Fabric Blueprint"
    test: "[T] Fabric Blueprint"
    prod: "[P] Fabric Blueprint"

  repository_directory: "."  # Relative to config.yml location

  parameter: "parameter.yml"  # References existing parameter.yml

publish:
  skip:
    dev: false
    test: false
    prod: false

unpublish:
  skip:
    dev: false
    test: false
    prod: false

features:
  - enable_experimental_features
  - enable_config_deploy
  - enable_shortcut_publish
